# Repo: mayar-1995/azure-test
# File: azure-test.yml
# Test
trigger:
- master
pool:
  vmImage: 'ubuntu-latest' 
resources:
   repositories:
     - repository: Templates
       type: github
       name: mayar-1995/resources
       endpoint: mayar-1995
jobs:
- job: Test
  steps:
  - task: CmdLine@2
    inputs:
     script: |
      ls
      pwd
      sudo apt-get install groovy
      chmod +x hiiii.groovy
      groovy hiiii.groovy


